export const PRODUCT_ROUTE = '/brand/tokiari/product/search'
export const PRODUCT_DETAIL_ROUTE = '/brand/tokiari/product/[id]'

export const ADMIN_ROUTE = '/admin'
export const ADMIN_LOGIN_ROUTE = '/admin/login'
export const ADMIN_USERS_ROUTE = '/admin/users'
export const ADMIN_USERS_DETAIL_ROUTE = '/admin/users/[id]'
export const ADMIN_SHIPPING_ROUTE = '/admin/shipping'
export const ADMIN_SHIPPING_DETAIL_ROUTE = '/admin/shipping/[id]'
export const ADMIN_ORDERS_ROUTE = '/admin/orders'
export const ADMIN_ORDERS_DETAIL_ROUTE = '/admin/orders/[id]'
export const ADMIN_REQUESTS_ROUTE = '/admin/requests'
export const ADMIN_REQUESTS_DETAIL_ROUTE = '/admin/requests/[id]'

export const ADMIN_PRODUCTS_ROUTE = '/admin/products'
export const ADMIN_PRODUCTS_DETAIL_ROUTE = '/admin/products/[id]'
export const ADMIN_PRODUCTS_DETAIL_EDIT_ROUTE = '/admin/products/[id]/edit'
export const ADMIN_PRODUCTS_DETAIL_VARIANT_CREATE_ROUTE = '/admin/products/[id]/variant-create'
export const ADMIN_PRODUCT_VARIANT_DETAIL_ROUTE = '/admin/products/[id]/[variantId]'
export const ADMIN_PRODUCT_VARIANT_DETAIL_EDIT_ROUTE = '/admin/products/[id]/[variantId]/edit'
export const ADMIN_PRODUCT_VARIANT_DETAIL_EDIT_IMAGE_ROUTE =
  '/admin/products/[id]/[variantId]/edit/images'
export const ADMIN_PRODUCTS_CREATE_ROUTE = '/admin/products/create'

export const WHOLESALE_ROUTE = '/wholesale'
export const WHOLESALE_CART_ROUTE = '/wholesale/cart'
export const WHOLESALE_ACCOUNT_ROUTE = '/wholesale/account'
export const WHOLESALE_PRODUCTS_DETAIL_ROUTE = '/wholesale/products/[id]'
export const WHOLESALE_WELCOME_ROUTE = '/wholesale/welcome'

// アカウント編集
export const WHOLESALE_ACCOUNT_EDIT_ROUTE = '/wholesale/account/edit'
export const WHOLESALE_ACCOUNT_EDIT_PASSWORD_ROUTE = '/wholesale/account/edit/password'
export const WHOLESALE_ACCOUNT_EDIT_EMAIL_ROUTE = '/wholesale/account/edit/email'

export const WHOLESALE_LOGIN_ROUTE = '/wholesale/login'
export const WHOLESALE_REQUEST_ROUTE = '/wholesale/request'
export const WHOLESALE_RESET_PASSWORD = '/wholesale/reset-password'
export const WHOLESALE_UPDATE_PASSWORD = '/wholesale/update-password'
export const WHOLESALE_AUTH_ROUTE = '/wholesale/auth'
export const WHOLESALE_AUTH_COMPLETE_ROUTE = '/wholesale/auth/complete'
export const WHOLESALE_REGISTER_ROUTE = '/wholesale/register'
export const WHOLESALE_REGISTER_COMPLETE_ROUTE = '/wholesale/register/complete'

export const REQUEST_ROUTE = '/request'
export const REQUEST_INPUT_ROUTE = '/request'
