import Provider from './provider'
import './globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="jp">
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  )
}
